#!/bin/sh
set -eu

APPDIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export LD_LIBRARY_PATH="${APPDIR}/usr/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas"
export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export GIO_MODULE_DIR="${APPDIR}/usr/lib/gio/modules"
export GIO_USE_VFS=local
export GDK_PIXBUF_MODULEDIR="${APPDIR}/usr/lib/gdk-pixbuf-loaders"
loader_cache=$(mktemp "${TMPDIR:-/tmp}/arboretum-pixbuf.XXXXXX")
trap 'rm -f "$loader_cache"' 0
export GDK_PIXBUF_MODULE_FILE="$loader_cache"
"${APPDIR}/usr/bin/gdk-pixbuf-query-loaders" > "$loader_cache"
"${APPDIR}/usr/bin/arboretum" "$@"
